// Importing necessary utilities from React Testing Library
import { render, screen } from '@testing-library/react';
// Importing the root component to test
import App from './App';

// This is a sample test case (auto-generated by Create React App)
test('renders learn react link', () => {
  // Render the App component into a virtual DOM for testing
  render(<App />);
  
  // Look for an element containing the text "learn react" (case-insensitive)
  const linkElement = screen.getByText(/learn react/i);
  
  // Assert that the element is actually present in the document
  expect(linkElement).toBeInTheDocument();
});
